name: Windows Build Cross-Compiling Meson

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  Build-Win:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt install g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64 llvm mingw-w64-tools nasm ninja-build
          python3 -m pip install meson
          
      - name: Install dependencies 1
        run: |
          vcpkg install spirv-cross:x64-mingw-dynamic

      - name: Install dependencies 2
        run: |
          vcpkg install spirv-cross:x64-linux
