name: Windows Build Cross-Compiling Meson

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  Build-Win:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
          
      - name: Download source code
        run: git clone --depth 1 --branch main https://github.com/KhronosGroup/SPIRV-Cross.git

      - name: Compile
        run: |
          cd SPIRV-Cross
          mkdir build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DSPIRV_CROSS_SHARED=ON -DSPIRV_CROSS_STATIC=OFF -DSPIRV_CROSS_CLI=OFF
          cmake --build build
          sudo cmake --install build
